In [1]:
import numpy as np

1. Решите линейную систему:

In [2]:
A = np.array([[1,2,3],[4,0,6],[7,8,9]])
B = np.array([12,2,1])
np.linalg.solve(A,B)

array([-9.2       ,  0.9       ,  6.46666667])

In [3]:
A1 = np.linalg.inv(A)
X = np.dot(A1,B)
X

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:

In [4]:
A = np.array([[1,2,-1],[3,-4,0],[8,-5,2],[2,0,-5],[11,4,-7]])
B = np.array([1,7,12,7,15])
np.linalg.lstsq(A,B)

C:\Users\marty\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

3. Сколько решений имеет линейная система:

In [5]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[12,2,1]])
np.linalg.matrix_rank(A)

2

In [6]:
C = np.concatenate((A,B.T), axis=1)
np.linalg.matrix_rank(C)

3

Т.к. ранг матрицы меньше ранга расширенной матрицы, система решений не имеет.

измените вектор правой части так, чтобы система стала совместной, и решите ее:

In [7]:
D = np.array([[1,2,3,12],[4,5,6,24],[7,8,9,36]])
D

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 24],
       [ 7,  8,  9, 36]])

In [8]:
np.linalg.matrix_rank(D)

2

In [9]:
B1 = np.array([12,24,36])
np.linalg.solve(A,B1)

array([0., 0., 4.])

4. Вычислите LU-разложение матрицы:

In [12]:
import scipy
import scipy.linalg
A = np.array([[1,2,3],[2,16,21],[4,28,73]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [13]:
B = np.array([4,6,8])
np.linalg.solve(A,B)

array([ 4.39814815, -0.00462963, -0.12962963])

5. Найдите нормальное псевдорешение недоопределенной системы: